// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package dal

import (
	"context"
)

const addApp = `-- name: AddApp :exec
INSERT INTO app (
        app_id,
        img_url
    )
VALUES (
        $1,
        $2
    )
`

type AddAppParams struct {
	AppID  string `json:"app_id"`
	ImgUrl string `json:"img_url"`
}

func (q *Queries) AddApp(ctx context.Context, arg AddAppParams) error {
	_, err := q.db.ExecContext(ctx, addApp, arg.AppID, arg.ImgUrl)
	return err
}
