// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: prover_network.proto

package serviceapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProverNetwork_RegisterApp_FullMethodName      = "/prover_network.ProverNetwork/RegisterApp"
	ProverNetwork_EstimateCost_FullMethodName     = "/prover_network.ProverNetwork/EstimateCost"
	ProverNetwork_ProveTask_FullMethodName        = "/prover_network.ProverNetwork/ProveTask"
	ProverNetwork_GetProvingResult_FullMethodName = "/prover_network.ProverNetwork/GetProvingResult"
)

// ProverNetworkClient is the client API for ProverNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProverNetworkClient interface {
	// register a new application with elf
	RegisterApp(ctx context.Context, in *RegisterAppRequest, opts ...grpc.CallOption) (*RegisterAppResponse, error)
	// estimate gas cost
	EstimateCost(ctx context.Context, in *EstimateCostRequest, opts ...grpc.CallOption) (*EstimateCostResponse, error)
	// add a proving task
	ProveTask(ctx context.Context, in *ProveTaskRequest, opts ...grpc.CallOption) (*ProveTaskResponse, error)
	// try to fetch the proving result if complete
	GetProvingResult(ctx context.Context, in *GetProvingResultRequest, opts ...grpc.CallOption) (*GetProvingResultResponse, error)
}

type proverNetworkClient struct {
	cc grpc.ClientConnInterface
}

func NewProverNetworkClient(cc grpc.ClientConnInterface) ProverNetworkClient {
	return &proverNetworkClient{cc}
}

func (c *proverNetworkClient) RegisterApp(ctx context.Context, in *RegisterAppRequest, opts ...grpc.CallOption) (*RegisterAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAppResponse)
	err := c.cc.Invoke(ctx, ProverNetwork_RegisterApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverNetworkClient) EstimateCost(ctx context.Context, in *EstimateCostRequest, opts ...grpc.CallOption) (*EstimateCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateCostResponse)
	err := c.cc.Invoke(ctx, ProverNetwork_EstimateCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverNetworkClient) ProveTask(ctx context.Context, in *ProveTaskRequest, opts ...grpc.CallOption) (*ProveTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProveTaskResponse)
	err := c.cc.Invoke(ctx, ProverNetwork_ProveTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proverNetworkClient) GetProvingResult(ctx context.Context, in *GetProvingResultRequest, opts ...grpc.CallOption) (*GetProvingResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProvingResultResponse)
	err := c.cc.Invoke(ctx, ProverNetwork_GetProvingResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProverNetworkServer is the server API for ProverNetwork service.
// All implementations should embed UnimplementedProverNetworkServer
// for forward compatibility.
type ProverNetworkServer interface {
	// register a new application with elf
	RegisterApp(context.Context, *RegisterAppRequest) (*RegisterAppResponse, error)
	// estimate gas cost
	EstimateCost(context.Context, *EstimateCostRequest) (*EstimateCostResponse, error)
	// add a proving task
	ProveTask(context.Context, *ProveTaskRequest) (*ProveTaskResponse, error)
	// try to fetch the proving result if complete
	GetProvingResult(context.Context, *GetProvingResultRequest) (*GetProvingResultResponse, error)
}

// UnimplementedProverNetworkServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProverNetworkServer struct{}

func (UnimplementedProverNetworkServer) RegisterApp(context.Context, *RegisterAppRequest) (*RegisterAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterApp not implemented")
}
func (UnimplementedProverNetworkServer) EstimateCost(context.Context, *EstimateCostRequest) (*EstimateCostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateCost not implemented")
}
func (UnimplementedProverNetworkServer) ProveTask(context.Context, *ProveTaskRequest) (*ProveTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProveTask not implemented")
}
func (UnimplementedProverNetworkServer) GetProvingResult(context.Context, *GetProvingResultRequest) (*GetProvingResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProvingResult not implemented")
}
func (UnimplementedProverNetworkServer) testEmbeddedByValue() {}

// UnsafeProverNetworkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProverNetworkServer will
// result in compilation errors.
type UnsafeProverNetworkServer interface {
	mustEmbedUnimplementedProverNetworkServer()
}

func RegisterProverNetworkServer(s grpc.ServiceRegistrar, srv ProverNetworkServer) {
	// If the following call pancis, it indicates UnimplementedProverNetworkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProverNetwork_ServiceDesc, srv)
}

func _ProverNetwork_RegisterApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverNetworkServer).RegisterApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverNetwork_RegisterApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverNetworkServer).RegisterApp(ctx, req.(*RegisterAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverNetwork_EstimateCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverNetworkServer).EstimateCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverNetwork_EstimateCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverNetworkServer).EstimateCost(ctx, req.(*EstimateCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverNetwork_ProveTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverNetworkServer).ProveTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverNetwork_ProveTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverNetworkServer).ProveTask(ctx, req.(*ProveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProverNetwork_GetProvingResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProvingResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProverNetworkServer).GetProvingResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProverNetwork_GetProvingResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProverNetworkServer).GetProvingResult(ctx, req.(*GetProvingResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProverNetwork_ServiceDesc is the grpc.ServiceDesc for ProverNetwork service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProverNetwork_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prover_network.ProverNetwork",
	HandlerType: (*ProverNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterApp",
			Handler:    _ProverNetwork_RegisterApp_Handler,
		},
		{
			MethodName: "EstimateCost",
			Handler:    _ProverNetwork_EstimateCost_Handler,
		},
		{
			MethodName: "ProveTask",
			Handler:    _ProverNetwork_ProveTask_Handler,
		},
		{
			MethodName: "GetProvingResult",
			Handler:    _ProverNetwork_GetProvingResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prover_network.proto",
}
